name: expense
description: Expense Tracker Mobile App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get:
  image_picker: ^0.8.4+11
  sqflite: ^2.0.2
  get_storage:
  printing: ^5.7.4
  charts_flutter: ^0.12.0
  excel: any
  percent_indicator: ^4.2.2
  path_provider:
  permission_handler:
  open_file: ^3.2.1
  file_picker: ^4.5.1
  shared_preferences: ^2.0.13
  intl:
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
