name: expense
description: Expense Tracker Mobile App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get:
  sqflite: ^2.0.2
  charts_flutter: ^0.12.0
  excel: any
  intl:
  image_picker: ^0.8.4+11
  cupertino_icons: ^1.0.2
  file_picker: ^5.2.5
  path_provider: ^2.0.12
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
